// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/cxapi"
	"github.com/fillmore-labs/microbatch-lambda/cdk/pkg/server"
)

// Injectors from wire.go:

func NewAssembly() cxapi.CloudAssembly {
	awscdkAppProps := _wireAppPropsValue
	app := awscdk.NewApp(awscdkAppProps)
	environment := env()
	lambdaStack := server.NewStack(app, environment)
	logGroup := server.NewLogGroup(lambdaStack)
	fn := server.NewFn(lambdaStack, logGroup)
	fnURL := server.NewFnURL(lambdaStack, fn)
	stack := server.Stack{
		Fn:          fn,
		FnURL:       fnURL,
		LambdaStack: lambdaStack,
	}
	cdkApp := CdkApp{
		App:         app,
		serverStack: stack,
	}
	cloudAssembly := CreateCloudAssembly(cdkApp)
	return cloudAssembly
}

var (
	_wireAppPropsValue = appProps
)
