// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
)

// Injectors from wire.go:

func NewStack(scope AppScope, environment *awscdk.Environment) Stack {
	stackProps := _wireStackPropsValue
	stack := newStack(scope, stackProps, environment)
	fn := NewFn(stack)
	fnURL := NewFnURL(stack, fn)
	serverStack := Stack{
		Fn:    fn,
		FnURL: fnURL,
		Stack: stack,
	}
	return serverStack
}

var (
	_wireStackPropsValue = StackProps{
		ID:          "MicrobatchLambdaStack",
		Description: "Microbatch test stack",
	}
)
